name: Node CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '12'
    - name: Install nodes packages
      run: npm install
    - name: Run tests
      run: npm test
    - name: Measure test coverage
      run: npm run coverage
    - name: Run linter
      run: npm run lint
    - name: Generate documentation
      run: npm run doc
    - name: Build
      run: npm run build