name: Node CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '12'
    - name: Install nodes packages
      run: npm ci
    - name: Run tests
      run: npm test
    - name: Measure test coverage
      run: npm run coverage
    - name: Run linter
      run: npm run lint
    - name: Generate documentation
      run: npm run doc
    - name: Build
      run: npm run build --if-present
    - name: Create Distributions (MergerJS)
      run: npm run merger
    - name: Archive code coverage results
      uses: actions/upload-artifact@v2
      with:
        name: code-coverage-report
        path: coverage
        retention-days: 31
        if-no-files-found: error
    - name: Archive documentation
      uses: actions/upload-artifact@v2
      with:
        name: documentation
        path: docs
        retention-days: 31
        if-no-files-found: error
    - name: Archive build artifacts
      uses: actions/upload-artifact@v2
      with:
        name: dist-without-markdown
        path: |
          dist
          !dist/**/*.md
        retention-days: 31
        if-no-files-found: error