name: Continuous Integration

on:
  push:
    branches:
      - master
    # Ignore changes in folders with generated contents or documentation.
    # Need to match git add parameters below.
    paths-ignore: 
      - 'coverage/**'
      - 'devdist/**'
      - 'dist/**'
      - 'docs/**'
      - '**/*.md'
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    env: 
      CI_COMMIT_MESSAGE: Continuous Integration Build Artifacts
      CI_COMMIT_AUTHOR: ${{ github.event.repository.name }} Continuous Integration
    steps:
    - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5
      with: 
        token: ${{ secrets.WORKFLOW_GIT_ACCESS_TOKEN }}
    - name: Get GIT tags for auto-changelog generation (startingVersion config option)
      run: git fetch --tags origin

    # Build
    - uses: actions/setup-node@v4
      with:
        node-version: '22.19.0' 
    - name: Install node packages
      run: npm ci
    - name: Build package (lint, test, build, package, merge)
      run: npm run package

    # Archive generated or updated files 
    - name: Archive code coverage results
      uses: actions/upload-artifact@v4
      with:
        name: test-code-coverage-report
        path: coverage
        retention-days: 14
        if-no-files-found: error
    - name: Archive documentation
      uses: actions/upload-artifact@v4
      with:
        name: documentation
        path: docs
        retention-days: 14
        if-no-files-found: error
    - name: Archive CHANGELOG.md
      uses: actions/upload-artifact@v4
      with:
        name: changelog
        path: CHANGELOG.md
        retention-days: 14
        if-no-files-found: error
    - name: Archive build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: distribution-production
        path: dist
        retention-days: 14
        if-no-files-found: error
    - name: Archive build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: distribution-development
        path: devdist
        retention-days: 14
        if-no-files-found: error
    
    # Commit and push all changed files
    - name: Display event name 
      if: env.is-auto-commit == false
      run: echo "github.event_name=${{ github.event_name }}"
    - name: Commit build artifacts (dist, devdist, docs, coverage)
      # Only run when a pull request gets merged or a commit is pushed to the main branch
      # git add parameters need to match paths-ignore parameters above
      # Git pull before add/commit/push to reduce race conditions on parallel builds
      if: github.event_name == 'push'
      run: |
        git config --global user.name '${{ env.CI_COMMIT_AUTHOR }}'
        git config --global user.email "7671054+JohT@users.noreply.github.com"
        git fetch origin
        git status
        git add coverage devdist dist docs *.md
        git commit -m "${{ env.CI_COMMIT_MESSAGE }}"
        git status
        git rebase --strategy-option=theirs origin/master --verbose
        git status
        git push --verbose